# Generated by Django 3.0.6 on 2020-07-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_auto_20200623_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.CharField(default='errands', max_length=120),
            preserve_default=False,
        ),
    ]
