# Generated by Django 3.0.6 on 2020-07-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0004_archive_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='inProgress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='time',
            name='timerStart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='time',
            name='timerTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='time',
            name='timerTimer',
            field=models.IntegerField(default=0),
        ),
    ]
