# Generated by Django 3.0.6 on 2020-07-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0005_auto_20200708_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='projectName',
        ),
    ]
