# Generated by Django 3.0.6 on 2020-07-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0006_auto_20200713_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='projectColor',
            field=models.CharField(default='magenta', max_length=120),
            preserve_default=False,
        ),
    ]
