# Generated by Django 3.0.6 on 2020-07-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0006_auto_20200713_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='projectName',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
