# Generated by Django 3.0.6 on 2020-07-14 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0007_task_projectcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='projectColor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='projectName',
        ),
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(default='magenta', on_delete=django.db.models.deletion.CASCADE, to='prod.Project'),
            preserve_default=False,
        ),
    ]
