# Generated by Django 3.0.6 on 2020-07-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0008_auto_20200714_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_id',
        ),
        migrations.AddField(
            model_name='task',
            name='projectColor',
            field=models.CharField(default='magenta', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='projectName',
            field=models.CharField(default='foo', max_length=120),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
