# Generated by Django 3.0.6 on 2020-07-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0009_auto_20200714_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='projectColor',
            field=models.CharField(default='bleu', max_length=120),
        ),
        migrations.AlterField(
            model_name='task',
            name='projectName',
            field=models.CharField(default='foo', max_length=120),
        ),
    ]
