# Generated by Django 3.0.6 on 2020-07-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0011_auto_20200714_0143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
