# Generated by Django 3.0.6 on 2020-07-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0012_auto_20200714_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='project_id',
        ),
    ]
