# Generated by Django 3.0.6 on 2020-07-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0013_auto_20200714_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='projectColor',
        ),
    ]
