# Generated by Django 3.0.6 on 2020-07-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0014_remove_task_project_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
