# Generated by Django 3.0.6 on 2020-07-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0015_auto_20200714_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='task_id',
            field=models.IntegerField(),
        ),
    ]
