# Generated by Django 3.0.6 on 2020-07-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0016_auto_20200714_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_color', to='prod.Project'),
        ),
        migrations.AlterField(
            model_name='time',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.Task'),
        ),
    ]
