# Generated by Django 3.0.6 on 2020-07-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0017_auto_20200714_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='timerTimer',
            new_name='timerInterval',
        ),
    ]
