# Generated by Django 3.0.6 on 2020-07-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0018_auto_20200714_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hex_color',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
