# Generated by Django 3.0.6 on 2020-07-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0019_project_hex_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_color', models.CharField(blank=True, max_length=120)),
                ('color', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='hex_color',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='color',
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_info', to='prod.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='color_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Color'),
        ),
    ]
