# Generated by Django 3.0.6 on 2020-07-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0020_auto_20200716_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='projectName',
        ),
    ]
