# Generated by Django 3.0.6 on 2020-07-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0021_remove_task_projectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Task'),
        ),
        migrations.AlterField(
            model_name='current',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Task'),
        ),
    ]
