# Generated by Django 3.0.6 on 2020-07-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0023_auto_20200716_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='foo',
            field=models.CharField(default='foo', max_length=120),
        ),
    ]
