# Generated by Django 3.0.6 on 2020-07-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0025_auto_20200716_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project_info',
        ),
    ]
