# Generated by Django 3.0.6 on 2020-07-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0026_auto_20200716_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='color_id',
        ),
        migrations.AddField(
            model_name='project',
            name='colors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='prod.Color'),
        ),
    ]
