# Generated by Django 3.0.6 on 2020-07-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0028_auto_20200716_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current',
            name='foo',
        ),
    ]
